//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirsoftBmsApp.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AirsoftBmsApp.Resources.Languages.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm your password.
        /// </summary>
        internal static string AccountConfirmPasswordInputPlaceholder {
            get {
                return ResourceManager.GetString("AccountConfirmPasswordInputPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter account email.
        /// </summary>
        internal static string AccountEmailInputPlaceholder {
            get {
                return ResourceManager.GetString("AccountEmailInputPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter account password.
        /// </summary>
        internal static string AccountPasswordInputPlaceholder {
            get {
                return ResourceManager.GetString("AccountPasswordInputPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Spawn Zone.
        /// </summary>
        internal static string AddSpawnZoneButtonText {
            get {
                return ResourceManager.GetString("AddSpawnZoneButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        internal static string AdminLabel {
            get {
                return ResourceManager.GetString("AdminLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alive.
        /// </summary>
        internal static string AliveValue {
            get {
                return ResourceManager.GetString("AliveValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string BackButton {
            get {
                return ResourceManager.GetString("BackButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fight.
        /// </summary>
        internal static string BattleFightStatusText {
            get {
                return ResourceManager.GetString("BattleFightStatusText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Battle is paused.
        /// </summary>
        internal static string BattleIsPausedMapMessage {
            get {
                return ResourceManager.GetString("BattleIsPausedMapMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter battle name.
        /// </summary>
        internal static string BattleNameInputPlaceholder {
            get {
                return ResourceManager.GetString("BattleNameInputPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battle name is required..
        /// </summary>
        internal static string BattleNameIsRequiredValidationMessage {
            get {
                return ResourceManager.GetString("BattleNameIsRequiredValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battle name must be under {0} characters long..
        /// </summary>
        internal static string BattleNameIsTooShortValidationMessage {
            get {
                return ResourceManager.GetString("BattleNameIsTooShortValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battle.
        /// </summary>
        internal static string BattleNavItemText {
            get {
                return ResourceManager.GetString("BattleNavItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paused.
        /// </summary>
        internal static string BattlePausedStatusText {
            get {
                return ResourceManager.GetString("BattlePausedStatusText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battle Settings.
        /// </summary>
        internal static string BattleSettingsHeader {
            get {
                return ResourceManager.GetString("BattleSettingsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - {0} killed.
        /// </summary>
        internal static string CasualtiesKilledText {
            get {
                return ResourceManager.GetString("CasualtiesKilledText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Casualties:.
        /// </summary>
        internal static string CasualtiesLabel {
            get {
                return ResourceManager.GetString("CasualtiesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Action.
        /// </summary>
        internal static string ChooseActionTitle {
            get {
                return ResourceManager.GetString("ChooseActionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string ConfirmButton {
            get {
                return ResourceManager.GetString("ConfirmButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password is required..
        /// </summary>
        internal static string ConfirmPasswordIsRequiredValidationMessage {
            get {
                return ResourceManager.GetString("ConfirmPasswordIsRequiredValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Battle.
        /// </summary>
        internal static string CreateBattleButton {
            get {
                return ResourceManager.GetString("CreateBattleButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string CreateButton {
            get {
                return ResourceManager.GetString("CreateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Room.
        /// </summary>
        internal static string CreateRoomButton {
            get {
                return ResourceManager.GetString("CreateRoomButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Room.
        /// </summary>
        internal static string CreateRoomHeader {
            get {
                return ResourceManager.GetString("CreateRoomHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Team.
        /// </summary>
        internal static string CreateTeamButton {
            get {
                return ResourceManager.GetString("CreateTeamButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Team.
        /// </summary>
        internal static string CreateTeamHeader {
            get {
                return ResourceManager.GetString("CreateTeamHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dead.
        /// </summary>
        internal static string DeadValue {
            get {
                return ResourceManager.GetString("DeadValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defend.
        /// </summary>
        internal static string DefendButtonText {
            get {
                return ResourceManager.GetString("DefendButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Room.
        /// </summary>
        internal static string DeleteRoomButton {
            get {
                return ResourceManager.GetString("DeleteRoomButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the room?.
        /// </summary>
        internal static string DeleteRoomConfirmationMessage {
            get {
                return ResourceManager.GetString("DeleteRoomConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Team.
        /// </summary>
        internal static string DeleteTeamButton {
            get {
                return ResourceManager.GetString("DeleteTeamButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete team {0}?.
        /// </summary>
        internal static string DeleteTeamConfirmationMessage {
            get {
                return ResourceManager.GetString("DeleteTeamConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong Email Format..
        /// </summary>
        internal static string EmailFormatValidationMessage {
            get {
                return ResourceManager.GetString("EmailFormatValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is required..
        /// </summary>
        internal static string EmailIsRequiredValidationMessage {
            get {
                return ResourceManager.GetString("EmailIsRequiredValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No one&apos;s here.
        /// </summary>
        internal static string EmptyTeamText {
            get {
                return ResourceManager.GetString("EmptyTeamText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to end the battle?.
        /// </summary>
        internal static string EndBattleConfirmationDialogMessage {
            get {
                return ResourceManager.GetString("EndBattleConfirmationDialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Networking error occured :/.
        /// </summary>
        internal static string ErrorHeader {
            get {
                return ResourceManager.GetString("ErrorHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - {0} in field.
        /// </summary>
        internal static string ForcesInFieldText {
            get {
                return ResourceManager.GetString("ForcesInFieldText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forces:.
        /// </summary>
        internal static string ForcesLabel {
            get {
                return ResourceManager.GetString("ForcesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide.
        /// </summary>
        internal static string HideButton {
            get {
                return ResourceManager.GetString("HideButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m Hit.
        /// </summary>
        internal static string HitButtonText {
            get {
                return ResourceManager.GetString("HitButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Paused.
        /// </summary>
        internal static string IsBattlePausedLabel {
            get {
                return ResourceManager.GetString("IsBattlePausedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join code must be exactly 6 characters, if provided..
        /// </summary>
        internal static string JoinCodeHas6CharactersValidationMessage {
            get {
                return ResourceManager.GetString("JoinCodeHas6CharactersValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter room join code.
        /// </summary>
        internal static string JoinCodeInputPlaceholder {
            get {
                return ResourceManager.GetString("JoinCodeInputPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join Room.
        /// </summary>
        internal static string JoinRoomButton {
            get {
                return ResourceManager.GetString("JoinRoomButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join Room.
        /// </summary>
        internal static string JoinRoomHeader {
            get {
                return ResourceManager.GetString("JoinRoomHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kick From Room.
        /// </summary>
        internal static string KickFromRoomButton {
            get {
                return ResourceManager.GetString("KickFromRoomButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kick From Team.
        /// </summary>
        internal static string KickFromTeamButton {
            get {
                return ResourceManager.GetString("KickFromTeamButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Down!.
        /// </summary>
        internal static string KillButtonText {
            get {
                return ResourceManager.GetString("KillButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave.
        /// </summary>
        internal static string LeaveButton {
            get {
                return ResourceManager.GetString("LeaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to leave your team?.
        /// </summary>
        internal static string LeaveTeamConfirmationMessage {
            get {
                return ResourceManager.GetString("LeaveTeamConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        internal static string LoadingMessage {
            get {
                return ResourceManager.GetString("LoadingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location is not available :/.
        /// </summary>
        internal static string LocationNotAvailableErrorMessage {
            get {
                return ResourceManager.GetString("LocationNotAvailableErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        internal static string LogInButton {
            get {
                return ResourceManager.GetString("LogInButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        internal static string LogInHeader {
            get {
                return ResourceManager.GetString("LogInHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Out.
        /// </summary>
        internal static string LogOutButton {
            get {
                return ResourceManager.GetString("LogOutButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map.
        /// </summary>
        internal static string MapNavItemText {
            get {
                return ResourceManager.GetString("MapNavItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark Enemy.
        /// </summary>
        internal static string MarkEnemyText {
            get {
                return ResourceManager.GetString("MarkEnemyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter max players number.
        /// </summary>
        internal static string MaxPlayersInputPlaceholder {
            get {
                return ResourceManager.GetString("MaxPlayersInputPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max players must be between 2 and 99999..
        /// </summary>
        internal static string MaxPlayersIsNotInRangeValidationMessage {
            get {
                return ResourceManager.GetString("MaxPlayersIsNotInRangeValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Players.
        /// </summary>
        internal static string MaxPlayersLabel {
            get {
                return ResourceManager.GetString("MaxPlayersLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move.
        /// </summary>
        internal static string MoveButtonText {
            get {
                return ResourceManager.GetString("MoveButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is required..
        /// </summary>
        internal static string NameIsRequiredValidationMessage {
            get {
                return ResourceManager.GetString("NameIsRequiredValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Battle Is Going On.
        /// </summary>
        internal static string NoBattleHeader {
            get {
                return ResourceManager.GetString("NoBattleHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string NoButton {
            get {
                return ResourceManager.GetString("NoButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string NoValue {
            get {
                return ResourceManager.GetString("NoValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Officer.
        /// </summary>
        internal static string OfficerLabel {
            get {
                return ResourceManager.GetString("OfficerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string OkButton {
            get {
                return ResourceManager.GetString("OkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter room join code (optional).
        /// </summary>
        internal static string OptionalJoinCodeInputPlaceholder {
            get {
                return ResourceManager.GetString("OptionalJoinCodeInputPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter room password (optional).
        /// </summary>
        internal static string OptionalRoomPasswordInputPlaceholder {
            get {
                return ResourceManager.GetString("OptionalRoomPasswordInputPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order {0} to.
        /// </summary>
        internal static string OrderPlayerText {
            get {
                return ResourceManager.GetString("OrderPlayerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OR.
        /// </summary>
        internal static string OrLine {
            get {
                return ResourceManager.GetString("OrLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        internal static string OtherButton {
            get {
                return ResourceManager.GetString("OtherButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain at least 1 digit..
        /// </summary>
        internal static string PasswordHasDigitValidationMessage {
            get {
                return ResourceManager.GetString("PasswordHasDigitValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain at least 1 lowercase letter..
        /// </summary>
        internal static string PasswordHasLowercaseLetterValidationMessage {
            get {
                return ResourceManager.GetString("PasswordHasLowercaseLetterValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain at least 1 special character..
        /// </summary>
        internal static string PasswordHasSpecialCharacterValidationMessage {
            get {
                return ResourceManager.GetString("PasswordHasSpecialCharacterValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain at least 1 uppercase letter..
        /// </summary>
        internal static string PasswordHasUppercaseLetterValidationMessage {
            get {
                return ResourceManager.GetString("PasswordHasUppercaseLetterValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be exactly 6 characters, if provided..
        /// </summary>
        internal static string PasswordIs6CharactersLongIfProvided {
            get {
                return ResourceManager.GetString("PasswordIs6CharactersLongIfProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be at least 10 characters long..
        /// </summary>
        internal static string PasswordIsLongerThanValidationMessage {
            get {
                return ResourceManager.GetString("PasswordIsLongerThanValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is required..
        /// </summary>
        internal static string PasswordIsRequiredValidationMessage {
            get {
                return ResourceManager.GetString("PasswordIsRequiredValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords do not match..
        /// </summary>
        internal static string PasswordsDontMatchValidationMessage {
            get {
                return ResourceManager.GetString("PasswordsDontMatchValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Linked.
        /// </summary>
        internal static string PlayerAccountLabel {
            get {
                return ResourceManager.GetString("PlayerAccountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D.
        /// </summary>
        internal static string PlayerDeathsLabel {
            get {
                return ResourceManager.GetString("PlayerDeathsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This player no longer exists. It had never existed....
        /// </summary>
        internal static string PlayerDoesntExistInformationMessage {
            get {
                return ResourceManager.GetString("PlayerDoesntExistInformationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Admin.
        /// </summary>
        internal static string PlayerIsAdminLabel {
            get {
                return ResourceManager.GetString("PlayerIsAdminLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Officer.
        /// </summary>
        internal static string PlayerIsOfficerLabel {
            get {
                return ResourceManager.GetString("PlayerIsOfficerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to K.
        /// </summary>
        internal static string PlayerKillsLabel {
            get {
                return ResourceManager.GetString("PlayerKillsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name must be 20 characters or fewer..
        /// </summary>
        internal static string PlayerNameIsUnder21CharactersLongValidationMessage {
            get {
                return ResourceManager.GetString("PlayerNameIsUnder21CharactersLongValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string PlayerNameLabel {
            get {
                return ResourceManager.GetString("PlayerNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Player.
        /// </summary>
        internal static string PlayerPicker {
            get {
                return ResourceManager.GetString("PlayerPicker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deaths.
        /// </summary>
        internal static string PlayerProfileDeathsLabel {
            get {
                return ResourceManager.GetString("PlayerProfileDeathsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kills.
        /// </summary>
        internal static string PlayerProfileKillsLabel {
            get {
                return ResourceManager.GetString("PlayerProfileKillsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string PlayerStatusLabel {
            get {
                return ResourceManager.GetString("PlayerStatusLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team.
        /// </summary>
        internal static string PlayerTeamLabel {
            get {
                return ResourceManager.GetString("PlayerTeamLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room {0}.
        /// </summary>
        internal static string RoomJoinCodeHeader {
            get {
                return ResourceManager.GetString("RoomJoinCodeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room.
        /// </summary>
        internal static string RoomNavItemText {
            get {
                return ResourceManager.GetString("RoomNavItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter room password.
        /// </summary>
        internal static string RoomPasswordInputPlaceholder {
            get {
                return ResourceManager.GetString("RoomPasswordInputPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room Settings.
        /// </summary>
        internal static string RoomSettingsHeader {
            get {
                return ResourceManager.GetString("RoomSettingsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string SaveButton {
            get {
                return ResourceManager.GetString("SaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        internal static string SignUpButton {
            get {
                return ResourceManager.GetString("SignUpButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        internal static string SignUpHeader {
            get {
                return ResourceManager.GetString("SignUpHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to switch to team {0}?.
        /// </summary>
        internal static string SwitchTeamConfirmationMessage {
            get {
                return ResourceManager.GetString("SwitchTeamConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to take admin role?.
        /// </summary>
        internal static string TakeAdminRoleConfirmationMessage {
            get {
                return ResourceManager.GetString("TakeAdminRoleConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to take officer role?.
        /// </summary>
        internal static string TakeOfficerConfirmationMessage {
            get {
                return ResourceManager.GetString("TakeOfficerConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter team name.
        /// </summary>
        internal static string TeamNameInputPlaceholder {
            get {
                return ResourceManager.GetString("TeamNameInputPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team name must be 20 characters or fewer..
        /// </summary>
        internal static string TeamNameIsUnder20CharactersLongValidationMessage {
            get {
                return ResourceManager.GetString("TeamNameIsUnder20CharactersLongValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string TeamNameLabel {
            get {
                return ResourceManager.GetString("TeamNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move To Another Team.
        /// </summary>
        internal static string TeamPicker {
            get {
                return ResourceManager.GetString("TeamPicker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team Settings.
        /// </summary>
        internal static string TeamSettingsHeader {
            get {
                return ResourceManager.GetString("TeamSettingsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter text.
        /// </summary>
        internal static string TextInputPlaceholder {
            get {
                return ResourceManager.GetString("TextInputPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Under No Flag.
        /// </summary>
        internal static string UnderNoFlagHeader {
            get {
                return ResourceManager.GetString("UnderNoFlagHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled error.
        /// </summary>
        internal static string UnhandledErrorMessage {
            get {
                return ResourceManager.GetString("UnhandledErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your username.
        /// </summary>
        internal static string UsernameInputPlaceholder {
            get {
                return ResourceManager.GetString("UsernameInputPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VS.
        /// </summary>
        internal static string VS {
            get {
                return ResourceManager.GetString("VS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome {0}!.
        /// </summary>
        internal static string WelcomePlayerHeader {
            get {
                return ResourceManager.GetString("WelcomePlayerHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With Account.
        /// </summary>
        internal static string WithAccountHeader {
            get {
                return ResourceManager.GetString("WithAccountHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Without Account.
        /// </summary>
        internal static string WithoutAccountHeader {
            get {
                return ResourceManager.GetString("WithoutAccountHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string YesButton {
            get {
                return ResourceManager.GetString("YesButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string YesValue {
            get {
                return ResourceManager.GetString("YesValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can only take officer role in your own team..
        /// </summary>
        internal static string YouCanOnlyTakeOfficerInYourTeamInformationMessage {
            get {
                return ResourceManager.GetString("YouCanOnlyTakeOfficerInYourTeamInformationMessage", resourceCulture);
            }
        }
    }
}
